# Generated by Django 4.1.1 on 2024-12-03 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorgeneral',
            name='especialidad',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='ciudad',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='pais',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
